#lang sicp
(#%require sicp-pict)

(define (frame-edge frame)
  (let ((e1 (vector-add (frame-origin frame) (frame-edge1 frame)))
        (e2 (vector-add (frame-origin frame) (frame-edge2 frame)))
        (e3 (vector-add (frame-origin frame) (vector-add (frame-edge1 frame)
                                                         (frame-edge2 frame))))
        (o (frame-origin frame)))
    (segments->painter (list (make-segment o e1)
                             (make-segment o e2)
                             (make-segment e1 e3)
                             (make-segment e2 e3)))))

;return middle position vector
(define (segment-midpoint segment)
  (vector-scale 0.5 (vector-add (segment-start segment) (segment-end segment))))

(define (frame-edges frame)
  (let ((e1 (vector-add (frame-origin frame) (frame-edge1 frame)))
        (e2 (vector-add (frame-origin frame) (frame-edge2 frame)))
        (e3 (vector-add (frame-origin frame) (vector-add (frame-edge1 frame)
                                                         (frame-edge2 frame))))
        (o (frame-origin frame)))
    (list (make-segment o e1)
          (make-segment o e2)
          (make-segment e1 e3)
          (make-segment e2 e3))))

(define (frame-diag frame)
  (let ((e1 (vector-add (frame-origin frame) (frame-edge1 frame)))
        (e2 (vector-add (frame-origin frame) (frame-edge2 frame)))
        (e3 (vector-add (frame-origin frame) (vector-add (frame-edge1 frame)
                                                         (frame-edge2 frame))))
        (o (frame-origin frame)))
    (segments->painter (list (make-segment o e3)
                             (make-segment e1 e2)))))

(define (frame-diamond frame)
  (define edges (frame-edges frame))
  (let ((d1 (segment-midpoint (list-ref edges 0)))
        (d2 (segment-midpoint (list-ref edges 1)))
        (d3 (segment-midpoint (list-ref edges 2)))
        (d4 (segment-midpoint (list-ref edges 3))))
    (segments->painter (list (make-segment d1 d2)
                             (make-segment d1 d3)
                             (make-segment d2 d4)
                             (make-segment d3 d4)))))

(paint (frame-edge (make-frame (vect 0.5 0.5) (vect 0.5 0) (vect 0 0.5))))
(paint (frame-diag (make-frame (vect 0.5 0.5) (vect 0.5 0) (vect 0 0.5))))
(paint (frame-diag (make-frame (vect 0.5 0.5) (vect 0 0.5) (vect 0.5 0))))
(paint (frame-diamond (make-frame (vect 0.5 0.5) (vect 0 0.5) (vect 0.5 0))))